### ISSUE TITLE
Update links

### ISSUE THREAD

**Issue by patcon** [GSA/us-digital-registry#43]
The repo description and some prominent links in the README need to be updated to point to the new subdomain

**Comment by dvito** [comment]
I just pushed an update to this, but I'll be taking a look at fixing some of the description and language more.

**Comment by laurenancona** [comment]
<img width="1018" alt="screen shot 2016-10-28 at 9 26 52 am" src="https://cloud.githubusercontent.com/assets/2152151/19808054/e7967f78-9cf0-11e6-9a08-4d4d32270121.png">
@patcon were you referring to this ^

**Comment by dvito** [comment]
Fixed repo description.
