### ISSUE TITLE
Non-official account cleanup?

### ISSUE THREAD

**Issue by nschonni** [GSA/us-digital-registry#45]
I was syncing data from the API and came across a few GitHub accounts that didn't turn out to be organizations in https://github.com/github/government.github.com/pull/582
haiyan-amsgit: Random personal user account
noaaedeval: Looks good, but not an Org account, just a since (shared?) user
usopm: Also looks like a regular user

**Comment by ryanwoldatwork** [comment]
Hi @nschonni,

Thanks for flagging these (long ago)! It looks like they've been cleaned up.

Going forward, quality issues related to the U.S. Digital Registry data can be created here: https://github.com/GSA/touchpoints/issues.
