### ISSUE TITLE
Error message when trying to add something

### ISSUE THREAD

**Issue by gbinal** [GSA/us-digital-registry#52]
https://usdigitalregistry.digitalgov.gov/admin/mobile_apps/new
and
https://usdigitalregistry.digitalgov.gov/admin/social_media/new

both result in an error message for me.  

<img width="1041" alt="Screen Shot 2019-06-26 at 2 06 16 PM" src="https://user-images.githubusercontent.com/633088/60203910-b33a6b80-981b-11e9-859c-5f539f9c1060.png">

**Comment by gbinal** [comment]
Same with:

https://usdigitalregistry.digitalgov.gov/admin/review_social_media

**Comment by dvito** [comment]
Good catch, prepping a fresh deployment.  Looks like something got missed in a quick patch.

**Comment by gbinal** [comment]
Cool.  Just fyi, also here - 

https://usdigitalregistry.digitalgov.gov/admin/review_mobile_apps

and maybe unrelated but here - https://usdigitalregistry.digitalgov.gov/admin/mobile_apps.csv

**Comment by dvito** [comment]
Deployed a patch late yesterday afternoon. going to re-test this morning then i'll close this if everything looks fine.
