### ISSUE TITLE
Define 'website' and 'digital service'

### ISSUE THREAD

**Issue by gbinal** [GSA/us-digital-registry#54]

**Comment by gbinal** [comment]
From [M-17-06](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2017/m-17-06.pdf):
* "Federal Agency public websites and digital services are defined here as online information
resources or services maintained in whole or in part by the departments and agencies in the
Executive Branch of the U.S. Federal Government that are operated by an agency, contractor, or
other organization on behalf of the agency."
* "Digital services include the delivery of digital information (i.e., data or content) and transactional services (e.g., online forms, benefits applications) across a variety of platforms, devices, and delivery mechanisms (e.g., websites, mobile applications, and social media)."

**Comment by ryanwoldatwork** [comment]
https://www.whitehouse.gov/wp-content/uploads/legacy_drupal_files/omb/memoranda/2017/m-17-06.pdf works! 

closing
