### ISSUE TITLE
Broken link to Registry Admin

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/us-digital-registry#56]
As a user, when I click on `https://usdigitalregistry.digitalgov.gov/admin`, I get redirected back to `https://usdigitalregistry.digitalgov.gov/`, and am not taken to the admin of the registry.

This link can be found on both of these pages:
- https://usdigitalregistry.digitalgov.gov/
- https://digital.gov/services/u-s-digital-registry/

And doesn't work from either of these pages.

**Comment by dvito** [comment]
This was resolved.  Thanks for reporting!
